apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pub-deployment.yaml
- sub-deployment.yaml
images:
- name: pub
- name: sub
secretGenerator:
- files:
  - credentials.json
  name: gcp-credentials
